// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkAsYkMFQM3tG1Pl0IEPV5TdF4xjaawM',
    appId: '1:287206464750:web:8aa0a435435be48c73e7ff',
    messagingSenderId: '287206464750',
    projectId: 'chat-55ec8',
    authDomain: 'chat-55ec8.firebaseapp.com',
    storageBucket: 'chat-55ec8.firebasestorage.app',
    measurementId: 'G-RVFNF57D5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UeQOfai2BcJ5uvVFzoNIVaKC2LYpIKM',
    appId: '1:287206464750:android:e8178d58ae67689a73e7ff',
    messagingSenderId: '287206464750',
    projectId: 'chat-55ec8',
    storageBucket: 'chat-55ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5P0_J2Z3E_awMM6WeIEX9CCcb-rcM-0',
    appId: '1:287206464750:ios:7bdddbdeaecc93e173e7ff',
    messagingSenderId: '287206464750',
    projectId: 'chat-55ec8',
    storageBucket: 'chat-55ec8.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5P0_J2Z3E_awMM6WeIEX9CCcb-rcM-0',
    appId: '1:287206464750:ios:7bdddbdeaecc93e173e7ff',
    messagingSenderId: '287206464750',
    projectId: 'chat-55ec8',
    storageBucket: 'chat-55ec8.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZkAsYkMFQM3tG1Pl0IEPV5TdF4xjaawM',
    appId: '1:287206464750:web:70a0b9d0aab5a94973e7ff',
    messagingSenderId: '287206464750',
    projectId: 'chat-55ec8',
    authDomain: 'chat-55ec8.firebaseapp.com',
    storageBucket: 'chat-55ec8.firebasestorage.app',
    measurementId: 'G-8E5CCGCWJM',
  );
}
